/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import classes.Company;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Morillo
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    
    Company CN = new Company(2,2,1,2,2,2,10,20,30,40,50,60,3000, 1, 1, 1, 1, 1, 2, 1, 2, 3, 2, 5, 5,5, 2, 4, 5,  10,20, 300, 650, 60,21) ;

    public InterfazPrincipal() {
        initComponents();
        
        JLabel[] CNContableLabels = {CNIngresosLabel,CNGastosLabel,CNBeneficiosLabel};
        JLabel[] CNDirectorLabels = {CNIngresosLabel,CNGastosLabel,CNBeneficiosLabel,CNDiasEntregaLabel,CNFaltasPMlabel,CNPMStateLabel,CNDirectorStateLabel,CNDescuentoPMLabel};
        JLabel[] CNPMLabels = {CNGastosLabel,CNDiasEntregaLabel,CNFaltasPMlabel,CNPMStateLabel,CNDescuentoPMLabel};
        JLabel[] CNDriveLabels = {CNGuionesDispoLabel,CNAnimDispoLabels,CNEscnDispoLabel,CNDoblDispoLabel,CNPlotDispoLabel,CNCapDispoLabel,CNCapPlotDispo};
        
        this.CN.getDirector().setLabels(CNContableLabels);
        this.CN.getAnimadores().setContablesLabel(CNContableLabels);
        this.CN.getGuionistas().setContablesLabel(CNContableLabels);
        this.CN.getEscenografos().setContablesLabel(CNContableLabels);
        this.CN.getDobladores().setContablesLabel(CNContableLabels);
        this.CN.getPlotwisters().setContablesLabel(CNContableLabels);
        this.CN.getAssembler().setContablesLabel(CNContableLabels);
        
        this.CN.getPM().setPMlabels(CNPMLabels);
        this.CN.getDirector().setLabels(CNDirectorLabels);
        
        this.CN.getDrive().setLabelsDrive(CNDriveLabels);
        
        CN.getDrive().loadLimits();
        CN.StartWorking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CNPlusGuionButton = new javax.swing.JButton();
        CNPlusAnimButton = new javax.swing.JButton();
        CNPlusDoblButton = new javax.swing.JButton();
        CNPlusEcsnButton = new javax.swing.JButton();
        CNPlusPltButton = new javax.swing.JButton();
        CNMinusGuionButton = new javax.swing.JButton();
        CNMinusAnimButton = new javax.swing.JButton();
        CNMinusDoblButton = new javax.swing.JButton();
        CNMinusEscnButton = new javax.swing.JButton();
        CNMinusPltButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CNPlusEnsmButton = new javax.swing.JButton();
        CNMinusEnsmButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CNPMStateLabel = new javax.swing.JLabel();
        CNDirectorStateLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CNFaltasPMlabel = new javax.swing.JLabel();
        CNDescuentoPMLabel = new javax.swing.JLabel();
        CNDiasEntregaLabel = new javax.swing.JLabel();
        CNIngresosLabel = new javax.swing.JLabel();
        CNGastosLabel = new javax.swing.JLabel();
        CNBeneficiosLabel = new javax.swing.JLabel();
        CNGuionesDispoLabel = new javax.swing.JLabel();
        CNAnimDispoLabels = new javax.swing.JLabel();
        CNDoblDispoLabel = new javax.swing.JLabel();
        CNEscnDispoLabel = new javax.swing.JLabel();
        CNPlotDispoLabel = new javax.swing.JLabel();
        CNCapDispoLabel = new javax.swing.JLabel();
        CNCapPlotDispo = new javax.swing.JLabel();
        CNNumGuionistasLabel = new javax.swing.JLabel();
        CNNumAnimadoresLabel = new javax.swing.JLabel();
        CNNumDobladoresLabel = new javax.swing.JLabel();
        CNNumEscenografosLabel = new javax.swing.JLabel();
        CNNumPlotwistersLabel = new javax.swing.JLabel();
        CNNumEnsambladoresLabel = new javax.swing.JLabel();
        CNNumWorkersLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1282, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Principal", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1282, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Disney", jPanel3);

        jLabel1.setText("Trabajadores Totales: ");

        jLabel2.setText("Guionistas:");

        jLabel3.setText("Animadores:");

        jLabel4.setText("Dobladores:");

        jLabel5.setText("Escenografos:");

        jLabel6.setText("Plotwisters: ");

        CNPlusGuionButton.setText("+");
        CNPlusGuionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPlusGuionButtonActionPerformed(evt);
            }
        });

        CNPlusAnimButton.setText("+");
        CNPlusAnimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPlusAnimButtonActionPerformed(evt);
            }
        });

        CNPlusDoblButton.setText("+");
        CNPlusDoblButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPlusDoblButtonActionPerformed(evt);
            }
        });

        CNPlusEcsnButton.setText("+");
        CNPlusEcsnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPlusEcsnButtonActionPerformed(evt);
            }
        });

        CNPlusPltButton.setText("+");
        CNPlusPltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPlusPltButtonActionPerformed(evt);
            }
        });

        CNMinusGuionButton.setText("-");
        CNMinusGuionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNMinusGuionButtonActionPerformed(evt);
            }
        });

        CNMinusAnimButton.setText("-");
        CNMinusAnimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNMinusAnimButtonActionPerformed(evt);
            }
        });

        CNMinusDoblButton.setText("-");
        CNMinusDoblButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNMinusDoblButtonActionPerformed(evt);
            }
        });

        CNMinusEscnButton.setText("-");
        CNMinusEscnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNMinusEscnButtonActionPerformed(evt);
            }
        });

        CNMinusPltButton.setText("-");
        CNMinusPltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNMinusPltButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Ensambladores: ");

        CNPlusEnsmButton.setText("+");
        CNPlusEnsmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNPlusEnsmButtonActionPerformed(evt);
            }
        });

        CNMinusEnsmButton.setText("-");
        CNMinusEnsmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNMinusEnsmButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("CARTOON NETWORK");

        jLabel9.setText("DRIVE:");

        jLabel10.setText("Guiones: ");

        jLabel11.setText("Animaciones:");

        jLabel12.setText("Doblajes:");

        jLabel13.setText("Escenas");

        jLabel14.setText("Plotwist: ");

        jLabel15.setText("Capitulos Disponibles:");

        jLabel16.setText("Caps con Plotwist Disponibles:");

        jLabel17.setText("DIAS PARA LA ENTREGA:");

        jLabel18.setText("Ingresos Brutos:");

        jLabel19.setText("Gastos:");

        jLabel20.setText("Beneficios: ");

        jLabel21.setText("Estado del PM:");

        jLabel22.setText("Estado del Director:");

        CNPMStateLabel.setText(" Label PM");

        CNDirectorStateLabel.setText("Label Director");

        jLabel23.setText("FaltasPM: ");

        jLabel24.setText("Dinero Descontado al PM:");

        CNFaltasPMlabel.setText("Faltas PM label");

        CNDescuentoPMLabel.setText("Desc PM label");

        CNDiasEntregaLabel.setText("Dias");

        CNIngresosLabel.setText("0");

        CNGastosLabel.setText("Gastos");

        CNBeneficiosLabel.setText("Beneficios");

        CNGuionesDispoLabel.setText("0");

        CNAnimDispoLabels.setText("0");

        CNDoblDispoLabel.setText("0");

        CNEscnDispoLabel.setText("0");

        CNPlotDispoLabel.setText("0");

        CNCapDispoLabel.setText("0");

        CNCapPlotDispo.setText("0");

        CNNumGuionistasLabel.setText("1");

        CNNumAnimadoresLabel.setText("1");

        CNNumDobladoresLabel.setText("1");

        CNNumEscenografosLabel.setText("1");

        CNNumPlotwistersLabel.setText("1");

        CNNumEnsambladoresLabel.setText("1");

        CNNumWorkersLabel.setText("6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(47, 47, 47)
                                .addComponent(CNPMStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CNFaltasPMlabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(31, 31, 31)
                                .addComponent(CNDirectorStateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CNDescuentoPMLabel))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(CNNumWorkersLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CNMinusEnsmButton)
                                    .addComponent(CNMinusAnimButton)
                                    .addComponent(CNMinusGuionButton)
                                    .addComponent(CNMinusPltButton)
                                    .addComponent(CNMinusDoblButton)
                                    .addComponent(CNMinusEscnButton))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(CNNumGuionistasLabel))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CNNumDobladoresLabel)
                                            .addComponent(CNNumAnimadoresLabel)
                                            .addComponent(CNNumEscenografosLabel)
                                            .addComponent(CNNumPlotwistersLabel)
                                            .addComponent(CNNumEnsambladoresLabel))))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(CNPlusGuionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CNPlusAnimButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CNPlusDoblButton))
                                            .addComponent(CNPlusPltButton))
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14))
                                                .addGap(27, 27, 27)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(CNGuionesDispoLabel)
                                                    .addComponent(CNAnimDispoLabels)
                                                    .addComponent(CNDoblDispoLabel)
                                                    .addComponent(CNEscnDispoLabel)
                                                    .addComponent(CNPlotDispoLabel)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(CNCapDispoLabel))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(CNCapPlotDispo)
                                                    .addGap(14, 14, 14)))))
                                    .addComponent(CNPlusEcsnButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 407, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CNDiasEntregaLabel)
                                    .addComponent(CNIngresosLabel)
                                    .addComponent(CNGastosLabel)
                                    .addComponent(CNBeneficiosLabel)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CNPlusEnsmButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(113, 113, 113))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CNNumWorkersLabel))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CNPlusGuionButton)
                            .addComponent(CNMinusGuionButton)
                            .addComponent(CNNumGuionistasLabel))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CNPlusAnimButton)
                            .addComponent(CNMinusAnimButton)
                            .addComponent(CNNumAnimadoresLabel))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CNPlusDoblButton)
                            .addComponent(CNMinusDoblButton)
                            .addComponent(CNNumDobladoresLabel))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CNPlusEcsnButton)
                            .addComponent(CNMinusEscnButton)
                            .addComponent(CNNumEscenografosLabel))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CNPlusPltButton)
                            .addComponent(CNMinusPltButton)
                            .addComponent(CNNumPlotwistersLabel))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(CNDiasEntregaLabel))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(CNBeneficiosLabel))
                                        .addGap(56, 56, 56))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel19)
                                                    .addComponent(CNGastosLabel)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel18)
                                                    .addComponent(CNIngresosLabel))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(CNPMStateLabel)
                                    .addComponent(jLabel23)
                                    .addComponent(CNFaltasPMlabel))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(CNDirectorStateLabel)
                                    .addComponent(jLabel24)
                                    .addComponent(CNDescuentoPMLabel)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(CNGuionesDispoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(CNAnimDispoLabels))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(CNDoblDispoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(CNEscnDispoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(CNPlotDispoLabel))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(CNCapDispoLabel))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CNCapPlotDispo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CNPlusEnsmButton)
                    .addComponent(CNMinusEnsmButton)
                    .addComponent(CNNumEnsambladoresLabel))
                .addGap(14, 14, 14))
        );

        TabbedPane.addTab("CartoonNetwork", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CNPlusGuionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPlusGuionButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getTrabajadoresTotales() >= this.CN.getTrabajadoresTotalesMax()) {
            JOptionPane.showMessageDialog(this, "Has superado el limite de trabajadores");
        }
        else {
        this.CN.getGuionistas().setDevelopersquantity(this.CN.getGuionistas().getDevelopersquantity()+1);
        this.CN.actTotalTrabajadores();
        this.CNNumGuionistasLabel.setText(String.valueOf(this.CN.getGuionistas().getDevelopersquantity()));
        }
    }//GEN-LAST:event_CNPlusGuionButtonActionPerformed

    private void CNPlusAnimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPlusAnimButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getTrabajadoresTotales() >= this.CN.getTrabajadoresTotalesMax()) {
            JOptionPane.showMessageDialog(this, "Has superado el limite de trabajadores");
        }
        else {
        this.CN.getAnimadores().setDevelopersquantity(this.CN.getAnimadores().getDevelopersquantity()+1);
        this.CN.actTotalTrabajadores();
        this.CNNumAnimadoresLabel.setText(String.valueOf(this.CN.getAnimadores().getDevelopersquantity()));}
    }//GEN-LAST:event_CNPlusAnimButtonActionPerformed

    private void CNPlusDoblButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPlusDoblButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getTrabajadoresTotales() >= this.CN.getTrabajadoresTotalesMax()) {
            JOptionPane.showMessageDialog(this, "Has superado el limite de trabajadores");
        } else {
        this.CN.getDobladores().setDevelopersquantity(this.CN.getDobladores().getDevelopersquantity()+1);
        this.CN.actTotalTrabajadores();
        this.CNNumDobladoresLabel.setText(String.valueOf(this.CN.getDobladores().getDevelopersquantity()));}
    }//GEN-LAST:event_CNPlusDoblButtonActionPerformed

    private void CNPlusEcsnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPlusEcsnButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getTrabajadoresTotales() >= this.CN.getTrabajadoresTotalesMax()) {
            JOptionPane.showMessageDialog(this, "Has superado el limite de trabajadores");
        } else {
        this.CN.getEscenografos().setDevelopersquantity(this.CN.getEscenografos().getDevelopersquantity()+1);
        this.CN.actTotalTrabajadores();
        this.CNNumEscenografosLabel.setText(String.valueOf(this.CN.getEscenografos().getDevelopersquantity()));}
    }//GEN-LAST:event_CNPlusEcsnButtonActionPerformed

    private void CNPlusPltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPlusPltButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getTrabajadoresTotales() >= this.CN.getTrabajadoresTotalesMax()) {
            JOptionPane.showMessageDialog(this, "Has superado el limite de trabajadores");
        } else {
        this.CN.getPlotwisters().setDevelopersquantity(this.CN.getPlotwisters().getDevelopersquantity()+1);
        this.CN.actTotalTrabajadores();
        this.CNNumPlotwistersLabel.setText(String.valueOf(this.CN.getPlotwisters().getDevelopersquantity()));}
    }//GEN-LAST:event_CNPlusPltButtonActionPerformed

    private void CNPlusEnsmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNPlusEnsmButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getTrabajadoresTotales() >= this.CN.getTrabajadoresTotalesMax()) {
            JOptionPane.showMessageDialog(this, "Has superado el limite de trabajadores");
        } else {
        this.CN.getAssembler().setAssemblerquantity(this.CN.getAssembler().getAssemblerquantity()+1);
        this.CN.actTotalTrabajadores();
        this.CNNumEnsambladoresLabel.setText(String.valueOf(this.CN.getAssembler().getAssemblerquantity()));}
    }//GEN-LAST:event_CNPlusEnsmButtonActionPerformed

    private void CNMinusGuionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNMinusGuionButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getGuionistas().getDevelopersquantity() == 1){
            JOptionPane.showMessageDialog(this, "Cada Rol debe tener al menos un trabajador");
        } else {
        this.CN.getGuionistas().setDevelopersquantity(this.CN.getGuionistas().getDevelopersquantity()-1);
        this.CN.actTotalTrabajadores();
        this.CNNumGuionistasLabel.setText(String.valueOf(this.CN.getGuionistas().getDevelopersquantity()));
        }
        
    }//GEN-LAST:event_CNMinusGuionButtonActionPerformed

    private void CNMinusAnimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNMinusAnimButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getAnimadores().getDevelopersquantity() == 1){
            JOptionPane.showMessageDialog(this, "Cada Rol debe tener al menos un trabajador");
        } else {
        this.CN.getAnimadores().setDevelopersquantity(this.CN.getAnimadores().getDevelopersquantity()-1);
        this.CN.actTotalTrabajadores();
        this.CNNumAnimadoresLabel.setText(String.valueOf(this.CN.getAnimadores().getDevelopersquantity()));
        }
    }//GEN-LAST:event_CNMinusAnimButtonActionPerformed

    private void CNMinusDoblButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNMinusDoblButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getDobladores().getDevelopersquantity() == 1){
            JOptionPane.showMessageDialog(this, "Cada Rol debe tener al menos un trabajador");
        } else {
        this.CN.getDobladores().setDevelopersquantity(this.CN.getDobladores().getDevelopersquantity()-1);
        this.CN.actTotalTrabajadores();
        this.CNNumDobladoresLabel.setText(String.valueOf(this.CN.getDobladores().getDevelopersquantity()));
        }
    }//GEN-LAST:event_CNMinusDoblButtonActionPerformed

    private void CNMinusEscnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNMinusEscnButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getEscenografos().getDevelopersquantity() == 1){
            JOptionPane.showMessageDialog(this, "Cada Rol debe tener al menos un trabajador");
        } else {
        this.CN.getEscenografos().setDevelopersquantity(this.CN.getEscenografos().getDevelopersquantity()-1);
        this.CN.actTotalTrabajadores();
        this.CNNumEscenografosLabel.setText(String.valueOf(this.CN.getEscenografos().getDevelopersquantity()));
        }
    }//GEN-LAST:event_CNMinusEscnButtonActionPerformed

    private void CNMinusPltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNMinusPltButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getPlotwisters().getDevelopersquantity() == 1){
            JOptionPane.showMessageDialog(this, "Cada Rol debe tener al menos un trabajador");
        } else {
        this.CN.getPlotwisters().setDevelopersquantity(this.CN.getPlotwisters().getDevelopersquantity()-1);
        this.CN.actTotalTrabajadores();
        this.CNNumPlotwistersLabel.setText(String.valueOf(this.CN.getPlotwisters().getDevelopersquantity()));
        }
    }//GEN-LAST:event_CNMinusPltButtonActionPerformed

    private void CNMinusEnsmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNMinusEnsmButtonActionPerformed
        // TODO add your handling code here:
        if (this.CN.getAssembler().getAssemblerquantity()== 1){
            JOptionPane.showMessageDialog(this, "Cada Rol debe tener al menos un trabajador");
        } else {
        this.CN.getAssembler().setAssemblerquantity(this.CN.getAssembler().getAssemblerquantity()-1);
        this.CN.actTotalTrabajadores();
        this.CNNumEnsambladoresLabel.setText(String.valueOf(this.CN.getAssembler().getAssemblerquantity()));
        }
    }//GEN-LAST:event_CNMinusEnsmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CNAnimDispoLabels;
    private javax.swing.JLabel CNBeneficiosLabel;
    private javax.swing.JLabel CNCapDispoLabel;
    private javax.swing.JLabel CNCapPlotDispo;
    private javax.swing.JLabel CNDescuentoPMLabel;
    private javax.swing.JLabel CNDiasEntregaLabel;
    private javax.swing.JLabel CNDirectorStateLabel;
    private javax.swing.JLabel CNDoblDispoLabel;
    private javax.swing.JLabel CNEscnDispoLabel;
    private javax.swing.JLabel CNFaltasPMlabel;
    private javax.swing.JLabel CNGastosLabel;
    private javax.swing.JLabel CNGuionesDispoLabel;
    private javax.swing.JLabel CNIngresosLabel;
    private javax.swing.JButton CNMinusAnimButton;
    private javax.swing.JButton CNMinusDoblButton;
    private javax.swing.JButton CNMinusEnsmButton;
    private javax.swing.JButton CNMinusEscnButton;
    private javax.swing.JButton CNMinusGuionButton;
    private javax.swing.JButton CNMinusPltButton;
    private javax.swing.JLabel CNNumAnimadoresLabel;
    private javax.swing.JLabel CNNumDobladoresLabel;
    private javax.swing.JLabel CNNumEnsambladoresLabel;
    private javax.swing.JLabel CNNumEscenografosLabel;
    private javax.swing.JLabel CNNumGuionistasLabel;
    private javax.swing.JLabel CNNumPlotwistersLabel;
    private javax.swing.JLabel CNNumWorkersLabel;
    private javax.swing.JLabel CNPMStateLabel;
    private javax.swing.JLabel CNPlotDispoLabel;
    private javax.swing.JButton CNPlusAnimButton;
    private javax.swing.JButton CNPlusDoblButton;
    private javax.swing.JButton CNPlusEcsnButton;
    private javax.swing.JButton CNPlusEnsmButton;
    private javax.swing.JButton CNPlusGuionButton;
    private javax.swing.JButton CNPlusPltButton;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
